CREATE TABLE SkatUser (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL UNIQUE,
    CreatedAt TEXT NOT NULL,
    IsActive BOOLEAN NOT NULL CHECK (IsActive IN (0,1))
);

CREATE TABLE SkatYear (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Label TEXT NOT NULL UNIQUE,
    CreatedAt TEXT NOT NULL,
    ModifiedAt TEXT NOT NULL,
    StartDate TEXT NOT NULL UNIQUE,
    EndDate TEXT NOT NULL UNIQUE
);

CREATE TABLE SkatUserYear (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    SkatUserId INTEGER NOT NULL,
    SkatYearId INTEGER NOT NULL,
    IsPaid BOOLEAN NOT NULL CHECK (IsPaid IN (0,1)),
    Amount INTEGER NOT NULL,
    FOREIGN KEY (SkatUserId) REFERENCES SkatUser(Id) ON DELETE CASCADE,
    FOREIGN KEY (SkatYearId) REFERENCES SkatYear(Id) ON DELETE CASCADE
);

-- DROP TABLE SkatYear;
-- DROP TABLE SkatUser;
-- DROP TABLE SkatUserYear;