CREATE TABLE User(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Email TEXT NOT NULL UNIQUE,
    NemId TEXT NOT NULL,
    CPR TEXT NOT NULL UNIQUE,
    CreatedAt TEXT NOT NULL,
    ModifiedAt TEXT NOT NULL,
    GenderId INTEGER NOT NULL,
    FOREIGN KEY(GenderId) REFERENCES Gender(Id)
);

CREATE TABLE Password(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    CreatedAt TEXT NOT NULL,
    PasswordHash TEXT NOT NULL,
    IsValid BOOLEAN NOT NULL CHECK (IsValid IN (0,1)),
    UserId INTEGER NOT NULL,
    FOREIGN KEY(UserId) REFERENCES User(Id) ON DELETE CASCADE
);

CREATE TABLE Gender(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Label TEXT NOT NULL UNIQUE
);

-- INSERT INTO Gender(Label) VALUES ('male');
-- INSERT INTO Gender(Label) VALUES ('female');
-- INSERT INTO Gender(Label) VALUES ('transgender');

-- DROP TABLE User;
-- DROP TABLE Gender;
-- DROP TABLE Password;
